---
# handlers file for ansible-role-rsyslog-client
- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  when: ansible_connection != 'chroot' and rsyslog_service_state != 'stopped'
